<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [ ]:
import numpy as np
import matplotlib

def n_task1(X, V):
    return X @ V

print(n_task1(np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]), np.array([1, 2, 3])))


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [ ]:
def n_task2(M, treshold):
    for i in range(len(M[0])):
        for j in range(len(M)):
            if M[i][j] > treshold:
                M[i][j] = 1
            else:
                M[i][j] = 0
    return M
print(n_task2(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 5.5))

<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
def n_task3_rows(mat):
    un_rows = []
    for i in range(mat.shape[0]):
        row = mat[i]
        unique_elements = np.unique(row)
        un_rows.append(unique_elements)
    return un_rows


def n_task3_columns(mat):
    un_cols = []
    for i in range(mat.shape[1]):
        column = mat[:, i]
        unique_elements = np.unique(column)
        un_cols.append(unique_elements)

    return un_cols

print(n_task3_rows(np.array([[2, 1], [2, 2]])))

<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def create_and_analyze_matrix(m, n):
    matrix = np.random.normal(loc=0, scale=1, size=(m, n))
    math_expectation_columns = np.mean(matrix, axis=0)
    math_expectation_rows = np.mean(matrix, axis=1)
    variance_columns = np.var(matrix, axis=0)
    variance_rows = np.var(matrix, axis=1)
    
    print(matrix)
    print("мат. ожидание по столбцам:", math_expectation_columns)
    print("мат. ожидание по рядам:", math_expectation_rows)
    print("дисперсия по столбцам:", variance_columns)
    print("дисперсия по рядам:", variance_rows)

    for i in range(m):
        plt.figure()
        plt.hist(matrix[i, :], edgecolor='black', color='orange')
        plt.title(f'Histogram of row #{i+1}')
        plt.xlabel('Value')
        plt.ylabel('frequency')
    for i in range(n):
        plt.figure()
        plt.hist(matrix[:, i], edgecolor='black', color='orange')
        plt.title(f'Histogram of column #{i+1}')
        plt.xlabel('Value')
        plt.ylabel('frequency')
    plt.show()
    pass

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [2]:
import numpy as np
import matplotlib
def n_task5(m, n, a, b):
    matrix = np.zeros((m, n))
    matrix[0, 0] = a
    for j in range(1, n):
        if matrix[0, j - 1] == a:
            matrix[0, j] = b
        else:
            matrix[0, j] = a

    for i in range(1, m):
        for j in range(n):
            if (matrix[i - 1, j] == a):
                matrix[i, j] = b
            else:
                matrix[i, j] = a
    return matrix
print(np.array([[3, 4, 3], [4, 3, 4], [3, 4, 3]]))

[[3 4 3]
 [4 3 4]
 [3 4 3]]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    image = np.zeros((m, n, 3), dtype=np.uint8)
    image[:, :] = background_color
    x_start = m // 2 - a // 2
    x_end = x_start + a
    y_start = n // 2 - b // 2
    y_end = y_start + b
    image[y_start:y_end, x_start:x_end] = rectangle_color
    plt.imshow(image)
    plt.show()
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    image = np.zeros((m, n, 3), dtype=np.uint8)
    image[:, :] = background_color
    for i in range(m):
        for j in range(n):
            if ((j - n // 2)**2 / a**2 + (i - m // 2)**2 / b**2) <= 1:
                image[i, j] = ellipse_color
    plt.imshow(image)
    plt.show()


<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [3]:
import collections
def n_task7(time_series, window):
    math_expectation = np.mean(time_series)
    variance = np.var(time_series)
    standard_deviation = np.std(time_series)
    local_max = []
    local_min = []
    for i in range(1, len(time_series) - 1):
        if time_series[i] > time_series[i - 1] and time_series[i] > time_series[i + 1]:
            local_max.append(time_series[i])
        elif time_series[i] < time_series[i - 1] and time_series[i] < time_series[i + 1]:
            local_min.append(time_series[i])
    moving_average = []
    sequence = collections.deque(maxlen=window)
    for item in time_series:
        sequence.append(item)
        moving_average.append(sum(sequence) / len(sequence))

    print("Математическое ожидание:", math_expectation)
    print("Дисперсия:", variance)
    print("Среднеквадратическое отклонение:", standard_deviation)
    print("Локальные максимумы:", local_max)
    print("Локальные минимумы:", local_min)
    print("Скользящее среднее:", moving_average)
    pass

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
def n_task8(vector):
    result = np.zeros((vector.shape[0], vector.shape[0]))
    for i in range(len(vector)):
        result[i, vector[i]] = 1
    return result